SELECT DOC_ID,PhraseScore AS Scores FROM
(Sm/sumw AS PhraseScore)
(SELECT DOC_ID, sum(FREQ) AS sumw FROM INVINDEX GROUP BY DOC_ID) AS A 
INNER JOIN
 (SELECT DOC_ID, sum(FREQ) AS Sm FROM INVINDEX WHERE WORD="Hello" OR WORD="World" GROUP BY DOC_ID) AS B 
ON A.DOC_ID=B.DOC_ID;