SELECT DOC_ID,WordFreq/DocSize AS PhraseScore FROM
(SELECT DOC_ID AS GDOC_ID, sum(FREQ) AS DocSize FROM INVINDEX GROUP BY GDOC_ID) AS TotalFreq 
INNER JOIN
(SELECT DOC_ID, sum(FREQ) AS WordFreq FROM INVINDEX WHERE WORD="Hello" OR WORD="World" GROUP BY DOC_ID) AS PhraseFreq 
ON TotalFreq.GDOC_ID=PhraseFreq.DOC_ID;