SELECT WORD, SUMOFSCORE/NODOC AS AVGSCORE FROM
  (SELECT SUM(SCORE) AS SUMOFSCORE, WORD, COUNT(SCORE) AS NODOC FROM
      (
        SELECT WORD, DOC_ID, FREQ/SFREQ AS SCORE FROM(
          ((SELECT SUM(FREQ) AS SFREQ, DOC_ID AS ADOC_ID FROM INVINDEX GROUP BY DOC_ID) AS A)
            INNER JOIN
          ((SELECT WORD, DOC_ID, FREQ FROM INVINDEX) AS B)
            ON A.ADOC_ID=B.DOC_ID
        )
    ) AS E
  GROUP BY WORD) AS F ORDER BY AVGSCORE DESC;